# Class Exercise

In [1]:
import numpy as np

In [58]:
arr1 = np.zeros(10)
arr1[5] = 1
print(arr1)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [11]:
arr2 = np.arange(10, 49)
print(arr2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [12]:
arr2[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [21]:
arr3 = np.random.randint(150, size=(10, 10))
print("The minimum number is ", np.min(arr3))
print("The maximum number is ", np.max(arr3))

The minimum number is  1
The maximum number is  148


In [23]:
arr4 = np.random.random(size=(30))
print(np.mean(arr4))

0.47918784702760875


In [27]:
arr5 = np.random.random((5,5))
print(arr5)

arr_max, arr_min = arr5.max(), arr5.min()
arr5 = (arr5 - arr_min)/(arr_max - arr_min)
print("Normalized array: ",arr5)

[[0.39442237 0.61178806 0.14320829 0.54262133 0.79811346]
 [0.42669    0.66363563 0.91109199 0.76701921 0.67677893]
 [0.55149402 0.0811275  0.44476549 0.91108309 0.39908657]
 [0.65903732 0.97800022 0.83989845 0.15308459 0.08787796]
 [0.38995337 0.86088946 0.77567363 0.41912067 0.36660296]]
Normalized array:  [[0.34931921 0.59167879 0.06921917 0.51455889 0.79942889]
 [0.38529714 0.64948807 0.92539831 0.76475926 0.66414266]
 [0.52445181 0.         0.40545106 0.92538838 0.35451973]
 [0.64436102 1.         0.84601855 0.0802311  0.00752666]
 [0.34433634 0.86942322 0.7744088  0.37685745 0.31830097]]


In [29]:
arr6 = np.random.random((5,3))
arr7 = np.random.random((3,2))

np.dot(arr6,arr7)

array([[0.21027251, 0.30563075],
       [0.22579155, 0.15350685],
       [0.48158055, 0.34506317],
       [0.89204762, 0.45875004],
       [0.43973566, 0.70789265]])

In [55]:
arr8 = np.random.random((3,3))
print(arr8)

method_1 =arr8.astype(int)
print(method_1)
round_off = np.floor(arr8)
print(round_off)
truncate_it = np.trunc(arr8)
print(truncate_it)


[[0.97383196 0.1481319  0.49218146]
 [0.41788216 0.82885152 0.88257452]
 [0.51698863 0.43365639 0.08619173]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [54]:
arr9 = np.zeros((5,5))
print(arr9)

arr9+=np.arange(5)
print(arr9)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [48]:
arr10 = np.linspace(0,1,12,endpoint=True)[1:-1]
print(arr10)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [40]:
A = np.random.random()
B = np.random.random()

are_equal = np.allclose(A,B)
print(are_equal)

False


In [42]:
arr11 = np.zeros(5, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print(arr11)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.))]


In [44]:
A = np.ones((5,5,3))
B = np.ones((5,5))
print(A * B[:,:,None])

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [57]:
arr12 = np.arange(25).reshape(5,5)
arr12[[0,1]] = arr12[[1,0]]
print(arr12)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
