In [1]:
import numpy as np
ex6 = np.array([[111,112],[222,333]])
ex7 = np.array([[100,101],[200,202]])

print(ex6 + ex7)

[[211 213]
 [422 535]]


In [3]:
np.add(ex6,ex7)

array([[211, 213],
       [422, 535]])

In [4]:
np.multiply(ex6,ex7)

array([[11100, 11312],
       [44400, 67266]])

In [5]:
np.subtract(ex6,ex7)

array([[ 11,  11],
       [ 22, 131]])

In [6]:
np.power(ex6,ex7)

array([[1049659969,          0],
       [         0, 1581269833]], dtype=int32)

In [7]:
np.divide(ex6,ex7)

array([[1.11      , 1.10891089],
       [1.11      , 1.64851485]])

In [9]:
np.mean(ex6)

194.5

In [10]:
np.median(ex6)

167.0

In [11]:
np.mean(ex7)

150.75

In [12]:
np.median(ex7)

150.5

In [20]:
arr = np.array([1,2,1,3,4,4,6,9])
np.unique(arr)

array([1, 2, 3, 4, 6, 9])

In [21]:
arr.dtype

dtype('int32')

In [22]:
arr.astype(float)

array([1., 2., 1., 3., 4., 4., 6., 9.])